[2021-08-10 02:11:39,606] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing.task_3 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-10 02:11:39,655] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.processing.task_3 2021-08-09T00:00:00+00:00 [queued]>
[2021-08-10 02:11:39,659] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-08-10 02:11:39,659] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-08-10 02:11:39,661] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-08-10 02:11:39,689] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2021-08-09T00:00:00+00:00
[2021-08-10 02:11:39,702] {standard_task_runner.py:52} INFO - Started process 215668 to run task
[2021-08-10 02:11:39,729] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag.processing', 'task_3', '2021-08-09T00:00:00+00:00', '--job-id', '17', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpvjw48y7q', '--error-file', '/tmp/tmpegpaehxu']
[2021-08-10 02:11:39,740] {standard_task_runner.py:77} INFO - Job 17: Subtask task_3
[2021-08-10 02:11:39,926] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.processing.task_3 2021-08-09T00:00:00+00:00 [running]> on host airflowvm
[2021-08-10 02:11:40,144] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag.processing
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2021-08-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-09T00:00:00+00:00
[2021-08-10 02:11:40,146] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-10 02:11:40,152] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-08-10 02:11:40,165] {subprocess.py:75} INFO - Output:
[2021-08-10 02:11:43,174] {subprocess.py:83} INFO - Command exited with return code 0
[2021-08-10 02:11:43,228] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag.processing, task_id=task_3, execution_date=20210809T000000, start_date=20210810T021139, end_date=20210810T021143
[2021-08-10 02:11:43,273] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-10 02:11:43,309] {local_task_job.py:151} INFO - Task exited with return code 0
